### Try reaching localhost
GET http://localhost:8080 HTTP/1.1
### Get all contacts
GET http://localhost:8080/contacts HTTP/1.1
### Get contact by _id
GET http://localhost:8080/contacts/6329c369d876ca3c2783bea9 HTTP/1.1
### Create contact 
POST http://localhost:8080/contacts HTTP/1.1
content-type: application/json
{
    "firstName":"Dylan",
    "lastName":"Messings", 
    "email":"dmessings@go.com", 
    "favoriteColor":"Grey"
}
### PUT contact 
PUT http://localhost:8080/contacts/6329c369d876ca3c2783bea9 HTTP/1.1
content-type: application/json 
{
    "firstName":"Sondra", 
    "lastName":"Hall", 
    "email":"test@gmail.com", 
    "favoriteColor":"pink"
} 
### DELETE contact 
DELETE http://localhost:8080/contacts/6329c422d876ca3c2783beaa HTTP/1.1

### Same requests on render
GET http://cse341-770w.onrender.com/contacts HTTP/1.1
### by _id on Render
GET http://cse341-770w.onrender.com/contacts/6329c369d876ca3c2783bea9 HTTP/1.1
### Create contact 
POST http://cse341-770w.onrender.com/contacts HTTP/1.1
content-type: application/json
{
    "firstName":"Dylan",
    "lastName":"Messings", 
    "email":"dmessings@go.com", 
    "favoriteColor":"Grey"
}
### PUT contact 
PUT http://cse341-770w.onrender.com/contacts/6329c369d876ca3c2783bea9 HTTP/1.1
content-type: application/json
{
    "firstName":"Sondra", 
    "lastName":"Hall", 
    "email":"test@gmail.com", 
    "favoriteColor":"pink"
} 
### DELETE contact 
DELETE http://cse341-770w.onrender.com/contacts/6329c422d876ca3c2783beaa HTTP/1.1
